-- Table: users
CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- -- Table: roles
-- CREATE TABLE roles (
--     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     role_name VARCHAR(50) NOT NULL UNIQUE,
--     description VARCHAR(255),
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Table: user_roles (Join table for many-to-many relationship)
-- CREATE TABLE user_roles (
--     user_id BIGINT NOT NULL,
--     role_id BIGINT NOT NULL,
--     assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (user_id, role_id),
--     FOREIGN KEY (user_id) REFERENCES users(id),
--     FOREIGN KEY (role_id) REFERENCES roles(id)
-- );

-- -- Table: notifications
-- CREATE TABLE notifications (
--     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     user_id BIGINT NOT NULL,
--     notification_type VARCHAR(10) NOT NULL,  -- Changed ENUM to VARCHAR
--     message TEXT NOT NULL,
--     status VARCHAR(10) DEFAULT 'PENDING',  -- Changed ENUM to VARCHAR
--     sent_at TIMESTAMP NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     FOREIGN KEY (user_id) REFERENCES users(id)
-- );