server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true             # Enable service discovery
          lowerCaseServiceId: true  # Make the service id case insensitive
      httpclient:
        connect-timeout: 1000       # Connection timeout in milliseconds
        response-timeout: 10s       # Response timeout in seconds
eureka:
  instance:
    preferIpAddress: true           # Use IP address instead of hostname
  client:
    registerWithEureka: true        # Register with Eureka server
    fetchRegistry: true             # Fetch registry from Eureka server
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

info:
  app:
    name: "gateway-server"
    description: "Gateway Server"
    version: "0.0.1"