server:
  port: 8090
spring:
  application:
    name: messages
  cloud:
    function:
      definition: messageSupplier # function Bean in Spring Cloud Stream.
    stream:
      bindings:
        messageSupplier-in-0: # Consumer Binding. 
          destination: users.event # Consumes messages from the Kafka topic
          group: ${spring.application.name}
        messageSupplier-out-0:  # Producer Binding.
          destination: messages.response  # Publishes messages to the Kafka topic
      kafka:
        binder:
          brokers:
            - localhost:9092
# Logging
logging:
  level:
    com:
      jc:
        messages: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

